# Site settings

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl = "/" # The subpath of your site, e.g. / or /blog
languageCode = "en-us"
languageLang = "en"
title = "My New Hugo Site"

# Build settings

# Set the destination the same as the Gulpfile for consistency
destination = "../dist/"

# Categories and tags disabled for an easier start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]

# Enable this to have links relativized by Hugo
# E.g,  if your /post/first/ page contains a link 
# to /about/, Hugo will rewrite the URL to ../../about/
relativeURLs = false

# Enable to have links open in new tab
hrefTargetBlank = false

[params.cloudinary]
cloud_name = "forestry-demo"
use_upload = true

[params.cloudinary.presets.default]
min_width = 300
max_width = 1200
fallback_width = 600
steps = 5
sizes = "(max-width: 768px) 100vw, 1024px"

[params.cloudinary.presets.default.params]
width = 600
height = 700
opacity = 100
radius = 20


# Site Params
[params]
description = '''
Write an awesome description for your new site here. You can edit this\
line in config.yml. It will appear in your document head meta (for\
Google search results) and in your RSS feed description.\
'''
author = "Your name"

# Site Menus
# See the Hugo docs for usage in layouts
# https://gohugo.io/content-management/menus/
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"


